pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    limit_req_zone $binary_remote_addr zone=http_req_limit:10m rate=10r/s;
    limit_conn_zone $binary_remote_addr zone=ws_conn_limit:10m;

    server {
        listen 80;

        location / {
            limit_req zone=http_req_limit burst=20 nodelay;

            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }

        location /api1/ {
            limit_conn ws_conn_limit 10;

            proxy_pass http://172.31.48.136:8080/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;

            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }

        location /api2/ {
            limit_req zone=http_req_limit burst=20 nodelay;

            proxy_pass http://172.31.48.136:8080/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}