name: Build and Push images to DockerHub

on:
  push:
    branches:
      - main
    tags: ["*@*"]
  workflow_dispatch:
    inputs:
      service:
       type: choice
       required: true
       options:
         - App
         - server

permissions:
  id-token: write
  contents: read
  
jobs:
  filter:
    runs-on: ubuntu-24.04
    outputs:
      services: ${{steps.set-output.outputs.services}}
      environment: ${{steps.set-output.outputs.environment}}
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1
        if: ${{github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main'}}
      - name: Filter to check changes
        id: filter
        uses: dorny/paths-filter@b41dfa943b1939b9b646f67753bfe35cf6e4de03 # v4.0.2
        if: ${{github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'main'}}
        with:
          filters: |
            App: "App/**"
            server: "server/**"
      - name: Setup outputs
        id: set-output
        run: |
            if [[ "${{github.event_name}}" == 'workflow_dispatch' ]]; then
            echo "services=[\"${{inputs.service}}\"]" >> "$GITHUB_OUTPUT"
            echo "environment=development" >> "$GITHUB_OUTPUT"

            elif [[ "${{github.ref_type}}" == 'tag' ]]; then
            tag=${GITHUB_REF_NAME}
            svc=${tag%%@*}
            echo "services=[\"$svc\"]" >> ${GITHUB_OUTPUT}
            echo "environment=production" >> ${GITHUB_OUTPUT}
            
            else
            echo 'services=${{steps.filter.outputs.changes}}' >> "$GITHUB_OUTPUT"
            echo "environment=staging" >> "$GITHUB_OUTPUT"
            fi

  build-push-images:
    runs-on: ubuntu-24.04
    if: ${{needs.filter.outputs.services != '[]' && needs.filter.outputs.services != ''}}
    needs: filter
    strategy:
      matrix:
        service: ${{fromJson(needs.filter.outputs.services)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a # v7.0.1
        with:
          fetch-depth: 0
            
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@5b9cf3909b54a280b6df6eee035755eb1f2fd611 # v4.2.0

      - name: Login to Dockerhub
        if: ${{ !env.ACT}}
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Compute Docker Tag
        id: compute-tag
        run: |

            raw_svc="${{matrix.service}}"
            echo "image_name=${raw_svc,,}" >> "$GITHUB_OUTPUT"
            
            if [[ "${{github.event_name}}" == 'workflow_dispatch' ]]; then
              echo "version=dev-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

            elif [[ "${{github.ref_type}}" == 'tag' ]]; then 
              raw_tag="${GITHUB_REF_NAME}"
              version="${raw_tag##*@}"
              echo "version=${version}" >> "$GITHUB_OUTPUT"

            else
              echo "version=sha-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"
            fi

      - name: build and push container images
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
         context: ${{matrix.service}}
         push: ${{ !env.ACT }}
         load: ${{ env.ACT == 'true' }}
         tags: ${{vars.DOCKERHUB_USERNAME}}/${{steps.compute-tag.outputs.image_name}}:${{steps.compute-tag.outputs.version}}

      - name: Write tags to a file
        run: |
          mkdir -p tag-output
          jq -n --arg svc "${{matrix.service}}" --arg ver "${{steps.compute-tag.outputs.version}}" \
          '{($svc): $ver}' > tag-output/${{matrix.service}}.json

      - name: upload tags as artifects
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tag-${{matrix.service}}
          path: tag-output/${{matrix.service}}.json
          retention-days: 1

  Merge-tags:
    needs: build-push-images
    runs-on: ubuntu-24.04
    outputs:
     tag-versions: ${{ steps.merge.outputs.tags }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: tag-*
          path: tag-output
          merge-multiple: true

      - name: Merge into single JSON object
        id: merge
        run: |
          merged=$(jq -s 'add' tag-output/*.json)
          echo "tags=$(echo "$merged" | jq -c .)" >> "$GITHUB_OUTPUT"

  Deploy:
    needs: [filter, Merge-tags]
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: ${{ fromJson(needs.filter.outputs.services) }}
      fail-fast: false
    steps:        
      # SSH into app instance to update env
      - name: ssh into ec2 to update env
        if: matrix.target == 'App'
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2 # v1.2.5
        with:
          host: ${{ secrets.EC2_HOST_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd app
            TAGS_JSON='${{ needs.Merge-tags.outputs.tag-versions }}'
            
            APP_TAG=$(echo "$TAGS_JSON" | jq -r '(.App // .app) // ""')      # Check if TAGS_JSON contains app and/or server
            SERVER_TAG=$(echo "$TAGS_JSON" | jq -r '.server // ""')          # If not return empty string
            
            # Only touch APP_TAG line if there is a new value for it
            if [ -n "$APP_TAG" ]; then
              sed -i '/^APP_TAG=/d' .env
              echo "APP_TAG=$APP_TAG" >> .env
            fi
            
            # Only touch SERVER_TAG line if there is a new value for it
            if [ -n "$SERVER_TAG" ]; then
              sed -i '/^SERVER_TAG=/d' .env
              echo "SERVER_TAG=$SERVER_TAG" >> .env
            fi
            
            docker compose -f docker-compose-app.yml pull
            docker compose -f docker-compose-app.yml up -d --remove-orphans


      # AWS Credentials (Needed for SSM execution)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::793168138853:role/Github_SSM_Role
          aws-region: ap-south-1

      # Execute commands to update env on a private instance using AWS SSM
      - name: Execute Remote Shell via AWS SSM (Server)
        if: matrix.target == 'server'
        run: |
          # Multiline shell script to execute on the remote EC2 instance
            COMMANDS=$(cat << 'EOF'
            cd app
            TAGS_JSON='${{ needs.Merge-tags.outputs.tag-versions }}'
                    
            APP_TAG=$(echo "$TAGS_JSON" | jq -r '(.App // .app) // ""')
            SERVER_TAG=$(echo "$TAGS_JSON" | jq -r '.server // ""')
                    
            if [ -n "$APP_TAG" ]; then
              sed -i '/^APP_TAG=/d' .env
              echo "APP_TAG=$APP_TAG" >> .env
            fi
                    
            if [ -n "$SERVER_TAG" ]; then
              sed -i '/^SERVER_TAG=/d' .env
              echo "SERVER_TAG=$SERVER_TAG" >> .env
            fi
                    
            docker compose -f docker-compose-server.yml pull
            docker compose -f docker-compose-server.yml up -d --remove-orphans
            EOF
            )
          
            # Format commands into JSON array for SSM
            COMMAND_JSON_ARRAY=$(echo "$COMMANDS" | jq -R -s -c 'split("\n")[:-1]')
          
            # Execute SSM send-command
            aws ssm send-command \
              --instance-ids "${{ secrets.EC2_INSTANCE_ID_SERVER }}" \
              --document-name "AWS-RunShellScript" \
              --comment "Deploying updated container tags" \
              --parameters "commands=$COMMAND_JSON_ARRAY" \
              --query "Command.CommandId" \
              --output text
        